### ISSUE TITLE
round poll result percentages

### ISSUE THREAD

**Issue by joshleblanc** [joshleblanc/YuelaBot#172]
Added by Cereal from nu75 committee#general

**Comment by laurenball** [comment]
hey @joshleblanc, I can pick this up!

**Comment by joshleblanc** [comment]
@laurenball Cool! You can click the gitpod icon in the readme to launch into a pre-configured workspace for the bot. You'll need to enter your discord api key into a .env file in the root. You can get one over here: https://discordapp.com/developers/applications/

Or you can just make the change without testing 😄 

Check out commands/poll_command.rb#102

**Comment by laurenball** [comment]
sounds good! what decimal point should I round to?

**Comment by joshleblanc** [comment]
That works :smile:
