### ISSUE TITLE
README.md broken link

### ISSUE THREAD

**Issue by ScalarJerk** [joshleblanc/YuelaBot#457]
it seems the owner doesn't have any active repositories so that an image link can exist. The travos-ic status link is broken because of it.
![image](https://github.com/joshleblanc/YuelaBot/assets/88853543/5beae075-16c4-41e2-b9d9-5b1075cce28c)
![image](https://github.com/joshleblanc/YuelaBot/assets/88853543/5c3f2cbd-ea45-4e9c-95a0-f22c3d04d14f)

**Comment by joshleblanc** [comment]
Fixed
